trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
- powershell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    choco apikey --key $env:CHOCO_KEY --source https://push.chocolatey.org/
    choco pack
    $pkgs = Get-ChildItem -Path *.nupkg
    choco push $pkgs[0].Name --source https://push.chocolatey.org/
  env:
    CHOCO_KEY: $(chocoKey)